name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-githubRunnerforTest-${{ github.run_id }}-${{ github.run_attempt }}
        image:custom-linux-637423511138.dkr.ecr.eu-west-1.amazonaws.com/runner:latest
    steps:
      - run: echo "Hello World Gents!"
      - run: whoami
      - run: cat /etc/passwd
      - run: cat /etc/os-release
